export const projects = {
    personal: [
        {
            title: 'Repoclone',
            img: 'repoclone.png',
            desc: 'An NPM package to clone multiple GitHub repos for a specified username or organization into the current working directory.',
            demo: 'https://www.npmjs.com/package/repoclone',
            source: 'https://github.com/MichaelFarquhar/repoclone',
            stack: ['NodeJS', 'Commander', 'Inquirer', 'NPM'],
        },
        {
            title: 'Lorem Picsum - Raycast',
            img: 'lorem-picsum.png',
            desc: 'A Raycast extension to easily generate placeholder images of any size, powered by Lorem Picsum @ https://picsum.photos',
            demo: 'https://www.raycast.com/michaelfarquhar/lorem-picsum',
            source: 'https://github.com/raycast/extensions/tree/d535fb8b9a77d92f5a8268123de859c4da571fdb/extensions/lorem-picsum/',
            stack: ['React', 'Typescript', 'Raycast API'],
        },
        {
            title: 'Astro Linksplash',
            img: 'astro-linksplash.png',
            desc: 'Astro Template - Minimal and user-friendly link-sharing splash page, inspired by Linktree.',
            demo: 'astro-linksplash.netlify.app/',
            source: 'https://github.com/MichaelFarquhar/astro-linksplash',
            stack: ['Astro', 'HTML5', 'Javascript', 'TailwindCSS'],
        },
        {
            title: 'Wordle Clone',
            img: 'wordle.png',
            desc: 'A wordle clone built with React and Typescript. Instead of one word per day, you can play an unlimited amount of times.',
            demo: 'https://wordle-like-app.netlify.app/',
            source: 'https://github.com/MichaelFarquhar/wordle-clone',
            stack: ['React', 'Typescript', 'Sass', 'Recoil'],
        },
        {
            title: 'Portfolio',
            img: 'portfolio.png',
            desc: 'You are on this site right now! This is an Astro static site, built upon a foundational starter template.',
            demo: 'https://michaelfarquhar.bio/',
            source: 'https://github.com/MichaelFarquhar/portfolio',
            stack: ['Astro', 'HTML5', 'Javascript', 'TailwindCSS', 'DaisyUI'],
        },
        {
            title: 'Random Japanese Kana',
            img: 'random-kana.png',
            desc: 'Web app randomizer for quizzing Japanese Hiragana and Katakana.',
            demo: 'https://japanese-random-kana.netlify.app/',
            source: 'https://github.com/MichaelFarquhar/japanese-random-kana',
            stack: ['React', 'Typescript', 'Sass', 'Recoil'],
        },
        {
            title: 'Q&A Forum',
            img: 'laravel-qna.png',
            desc: 'Questions and answers forum built with Laravel 9.0, bootstrapped with Laravel Breeze. A simple CRUD application to emulate a site similar to Quora.',
            demo: '',
            source: 'https://github.com/MichaelFarquhar/laravel-qna-forum',
            stack: ['Laravel 9', 'Blade', 'AlpineJS', 'TailwindCSS'],
        },
        {
            title: 'StackShot',
            img: 'stackshot.png',
            desc: 'Create a custom snapshot of your software stack and download the image for use on your github repos.',
            demo: 'https://stackshotapp.netlify.app/',
            source: 'https://github.com/MichaelFarquhar/stackshot',
            stack: ['React', 'Typescript', 'Material UI', 'Recoil'],
        },
    ],
    freelance: [
        {
            title: 'Motor Cities Shuttles',
            img: 'motorcityshuttles.png',
            desc: 'A project contracted out to me by my previous employer at Digital Media. This is a simple website landing page built with PHP, SASS and MySQL.',
            demo: 'https://motorcitiesshuttle.com/',
            source: '',
            stack: ['PHP', 'Sass', 'MySQL'],
        },
        {
            title: 'Augustos Grill',
            img: 'augustos.png',
            desc: 'Website for a local restaurant opening in Leamington, Ontario. This site is built with Wordpress and Spectra page builder, using the Astra Theme.',
            demo: 'https://augustosgrill.com',
            source: '',
            stack: ['WordPress', 'Spectra', 'Astra'],
        },
        {
            title: 'Ambassador Golf Club',
            img: 'ambassador.png',
            desc: 'Provided minor updates to the Ambassador Golf Club website. Editing content and images, improving page speed and SEO, fixing design inconsistencies and various other minor improvements.',
            demo: 'https://ambassadorgolfclub.com/',
            source: '',
            stack: ['WordPress', 'Elementor'],
        },
        {
            title: 'Mike Farquhar',
            img: 'mike-farquhar.png',
            desc: 'My website home page for my freelancing web agency business. This site is built with Wordpress and Spectra page builder, using the Astra Theme.',
            demo: 'https://mikefarquhar.com',
            source: '',
            stack: ['WordPress', 'Spectra', 'Astra'],
        },
        {
            title: 'VapeVine',
            img: 'vapevine.png',
            desc: 'A website I briefly worked on, providing minor CSS/theme updates and general maintenance such as plugin updates.',
            demo: 'https://vapevine.ca/',
            source: '',
            stack: ['WordPress', 'WooCommerce'],
        },
    ],
    work: [
        {
            title: 'Spitsgear',
            img: 'spitsgear.png',
            desc: 'Online e-commerce website for the Windsor Spitsfires merchandise store. Custom built shopping cart using React, PHP and MySQL.',
            demo: 'https://spitsgear.com',
            source: '',
            stack: ['React', 'Redux', 'Sass', 'PHP', 'MySQL'],
        },
        {
            title: 'Muscedere Vineyards',
            img: 'muscedere.png',
            desc: 'A second example of a shopping cart site, built with the same stack. Online store for a local Winery in Harrow, Ontario.',
            demo: 'https://shop.muscederevineyards.com/',
            source: '',
            stack: ['React', 'Redux', 'Sass', 'PHP', 'MySQL'],
        },
        {
            title: 'Digital Media',
            img: 'digital-media.png',
            desc: 'Redesigned home page of Digital Media. Built with PHP, Sass and MySQL.',
            demo: 'https://digitalmedia.ca/',
            source: '',
            stack: ['LAMP', 'PHP', 'Sass', 'MySQL'],
        },
        {
            title: 'Rothmosey',
            img: 'rothmosey.png',
            desc: 'An example of the typical website built at Digital Media, using with an in-house PHP framework.',
            demo: 'https://rothmosey.com/',
            source: '',
            stack: ['LAMP', 'PHP', 'Sass', 'MySQL'],
        },
        {
            title: 'Oxley Estate Winery',
            img: 'oxley.png',
            desc: 'A second example of the typical website.',
            demo: 'https://oxleyestatewinery.com/',
            source: '',
            stack: ['LAMP', 'PHP', 'Sass', 'MySQL'],
        },
        {
            title: 'Pursuit Challenge',
            img: 'pursuitchallenge.png',
            desc: 'A Laravel application that is no longer being supported. A fitness challenge web application where users could create or join a team and compete agaisnt other users. Built with Laravel 7, Blade, Bootstrap and MySQL.',
            demo: 'https://www.facebook.com/pursuitchallenge.official/',
            source: '',
            stack: ['Laravel', 'Bootstrap', 'PHP', 'MySQL'],
        },
    ],
};
