export const projects = {
    personal: [
        {
            title: 'Repoclone',
            img: 'https://i.imgur.com/0DDnb2m.png',
            desc: 'An NPM package to clone multiple GitHub repos for a specified username or organization into the current working directory. ',
            demo: 'https://www.npmjs.com/package/repoclone',
            source: 'https://github.com/MichaelFarquhar/repoclone',
            stack: ['NodeJS', 'Commander', 'Inquirer', 'NPM'],
        },
        {
            title: 'Lorem Picsum - Raycast',
            img: 'https://i.imgur.com/9m31ECc.png',
            desc: 'A Raycast extension to easily generate placeholder images of any size, powered by Lorem Picsum @ https://picsum.photos',
            demo: 'https://www.raycast.com/michaelfarquhar/lorem-picsum',
            source: 'https://github.com/raycast/extensions/tree/d535fb8b9a77d92f5a8268123de859c4da571fdb/extensions/lorem-picsum/',
            stack: ['React', 'Typescript', 'Raycast API'],
        },
        {
            title: 'Astro Linksplash',
            img: 'https://i.imgur.com/doWnxEF.png',
            desc: 'Astro Template - Minimal and user-friendly link-sharing splash page, inspired by Linktree.',
            demo: 'astro-linksplash.netlify.app/',
            source: 'https://github.com/MichaelFarquhar/astro-linksplash',
            stack: ['Astro', 'HTML5', 'Javascript', 'TailwindCSS'],
        },
        {
            title: 'Wordle Clone',
            img: 'https://i.imgur.com/rjyjMLG.png',
            desc: 'A wordle clone built with React and Typescript. Instead of one word per day, you can play an unlimited amount of times.',
            demo: 'https://wordle-like-app.netlify.app/',
            source: 'https://github.com/MichaelFarquhar/wordle-clone',
            stack: ['React', 'Typescript', 'Sass', 'Recoil'],
        },
        {
            title: 'Q&A Forum',
            img: 'https://i.imgur.com/Bvr4tNg.png',
            desc: 'Questions and answers forum built with Laravel 9.0, bootstrapped with Laravel Breeze. A simple CRUD application to emulate a site similar to Quora.',
            demo: '',
            source: 'https://github.com/MichaelFarquhar/laravel-qna-forum',
            stack: ['Laravel 9', 'Blade', 'AlpineJS', 'TailwindCSS'],
        },
        {
            title: 'Portfolio',
            img: 'https://i.imgur.com/vU1162c.png',
            desc: 'You are on this site right now! This iteration of the design builds upon a foundational starter template, created by Manuel Ernesto.',
            demo: '',
            source: 'https://github.com/MichaelFarquhar/portfolio',
            stack: ['Astro', 'HTML5', 'Javascript', 'TailwindCSS', 'DaisyUI'],
        },
        {
            title: 'StackShot',
            img: 'https://i.imgur.com/Mcrn0GX.png',
            desc: 'Create a custom snapshot of your software stack and download the image for use on your github repos.',
            demo: 'https://stackshotapp.netlify.app/',
            source: 'https://github.com/MichaelFarquhar/stackshot',
            stack: ['React', 'Typescript', 'Material UI', 'Recoil'],
        },
        {
            title: 'Random Japanese Kana',
            img: 'https://i.imgur.com/cMB1A71.png',
            desc: 'Web app randomizer for quizzing Japanese Hiragana and Katakana.',
            demo: 'https://japanese-random-kana.netlify.app/',
            source: 'https://github.com/MichaelFarquhar/japanese-random-kana',
            stack: ['React', 'Typescript', 'Sass', 'Recoil'],
        },
    ],
    work: [
        {
            title: 'Spitsgear',
            img: 'https://i.imgur.com/QISsbi1.png',
            desc: 'Custom built shopping cart for Windsor Spitsfear merchandise store.',
            demo: 'https://spitsgear.com',
            source: '',
            stack: ['React', 'Sass', 'PHP', 'MySQL'],
        },
        {
            title: 'Digital Media',
            img: 'https://i.imgur.com/mo8y5mB.png',
            desc: 'Home page of current place of employment.',
            demo: 'https://digitalmedia.ca/',
            source: '',
            stack: ['LAMP', 'PHP', 'Sass', 'JQuery'],
        },
        {
            title: 'Rothmosey',
            img: 'https://i.imgur.com/ejdWu12.png',
            desc: 'An example of our typical websites we build, using with an in-house PHP framework.',
            demo: 'https://rothmosey.com/',
            source: '',
            stack: ['LAMP', 'PHP', 'Sass', 'JQuery'],
        },
        {
            title: 'South Asian Centre of Windsor',
            img: 'https://i.imgur.com/rY7rGTW.png',
            desc: 'Another example of our typical websites.',
            demo: '',
            source: '',
            stack: ['LAMP', 'PHP', 'Sass', 'JQuery'],
        },
        {
            title: 'Pursuit Challenge',
            img: 'https://i.imgur.com/pDtzceR.png',
            desc: 'React website with a PHP rest apt. The react code was built fully from scratch, utilizing react hookpurs.',
            demo: 'https://www.pursuitchallenge.com/',
            source: '',
            stack: ['React', 'Redux', 'Sass', 'PHP'],
        },
    ],
};
